[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending = "9XCHC5dVRNSkZvmMNj9F9ZQXPfXYjD6BQH2trTtkqBs5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
